### PR TITLE
template survival module

### PR DESCRIPTION
**Pull request by Dekken**
#175

### CODE REVIEW

**Comment by Mbompr** [comment]
Was it necessary to also template ModelSCCS? I'm a bit afraid that this would lead to very bad conflicts with #158 ...

**Comment by Dekken** [comment]
understandable - yet templating half the module seemed a bit peculiar

we'll see what Maryan thinks, I've not changed any functionality.

**Comment by MaryanMorel** [comment]
You're just using templating to allow multiple datatypes for coeffs in ModelSCCS right? In this case, it seems ok

**Comment by MaryanMorel** [comment]
The rebase won't be that hard regaring ModelSCCS I think

**Comment by Dekken** [comment]
I'll revert SCCS and update it after you have merged to be safe - only need

**Pull request closed without merging**
