### PR TITLE
Add python and C++ benchmarks

### PR DESCRIPTION
**Pull request by Mbompr**
Do #90

### CODE REVIEW

**Comment by Mbompr** [comment]
@Dekken Does cmake fails at linking on your linux computer as well? (cf travis build)

**Comment by Dekken** [comment]
yep - with pthread_create undefined link error

**Comment by Dekken** [comment]
this looks like it's missing a rebase, I'll have a look tomorow

**Comment by Mbompr** [comment]
Most of it has been merged in #164. Maybe can we extract some of this instead of rebasing the whole thing.

**Comment by Dekken** [comment]
is this obsoleted by https://github.com/X-DataInitiative/tick/pull/267 ?

**Pull request closed without merging**
