### PR TITLE
Added optional rotation of x_ticklabels for plot_hawkes_kernel_norms

### PR DESCRIPTION
**Pull request by timleathart**

### CODE REVIEW

**Comment by timleathart** [comment]
I found that when using custom node labels that are more than a couple of letters, the ticklabels would overlap, making them unreadable

**Comment by Mbompr** [comment]
Thanks for this PR, it makes sense indeed if the node labels are too long!

**Comment by Dekken** [comment]
Hi @timleathart - would you mind rebasing to master and we'll get this merged!

**Comment by Mbompr** [comment]
The command is simply `git pull --rebase origin master`

**Comment by timleathart** [comment]
Sorry, I'm not extremely proficient with git but I think I did the right thing?

**Comment by Mbompr** [comment]
Hi @timleathart, thanks for giving this a try. 
The procedure is well detailed [here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request). If you are having any problem with this, you can give me push access to you timleathart/tick repository and I can manage to do this.
Don't hesitate to ping us on [gitter](https://gitter.im/xdata-tick) if you're facing problems.

**Comment by Mbompr** [comment]
@Dekken has rebased it in #310. I'll merge this one, I hope you don't mind. Thanks for this PR!

**Pull request closed without merging**
