### PR TITLE
TICK-372 Using raw memory allocators, Python 3.6 in Travis

### PR DESCRIPTION
**Pull request by vinther**
Only significant change is that we now use `PyMem_Raw*` functions.'

Also added Python 3.6 to the list of tested versions for Travis.

### CODE REVIEW

**Comment by vinther** [comment]
Still need to fix the debug allocation counter

**Comment by vinther** [comment]
Change is needed because of https://docs.python.org/3/whatsnew/3.6.html#changes-in-the-c-api

**Comment by stephanegaiffas** [comment]
Weird error in travis :
```bash
The command "./build_test.sh" exited with 0.0.30s
$ export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR} && (cd doc && pyenv local ${PYVER} && make doctest)
sphinx-build -b doctest -d _build/doctrees   . _build/doctest
make: sphinx-build: No such file or directory
make: *** [doctest] Error 1
/Users/travis/.travis/job_stages: line 54: shell_session_update: command not found
The command "export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR} && (cd doc && pyenv local ${PYVER} && make doctest)" exited with 2.
cache.2
store build cache
0.03s
70.62sWarning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.
changes detected, packing new archive
uploading archive
Done. Your build exited with 1.
/Users/travis/.travis/job_stages: line 152: shell_session_update: command not found
```

**Comment by vinther** [comment]
Yes it's failing and it's incredibly frustrating!

**Comment by vinther** [comment]
Should succeed on Travis, and ready to be reviewed

**Pull request merged**
