### PR TITLE
Create lgtm.yml

### PR DESCRIPTION
**Pull request by Dekken**
successful build: https://lgtm.com/logs/81490e1791b04537a40f6366d2b42f4b5bdb7a32/lang:cpp

### CODE REVIEW

**Comment by Mbompr** [comment]
Is this meant to replace appveyor ? Or is it an additional build tool ?

**Comment by Dekken** [comment]
> Is this meant to replace appveyor ? Or is it an additional build tool ?

it's an additional tool that does code scanning/review similar to linting / PEP checks

**Comment by Dekken** [comment]
python coverage is already done https://lgtm.com/projects/g/X-DataInitiative/tick/

this PR adds C++ coverage

**Comment by Mbompr** [comment]
Thanks for the info !

**Pull request merged**
