### PR TITLE
keep appveory from updating to tf 2.0

### PR DESCRIPTION
**Pull request by Dekken**

### CODE REVIEW

**Comment by Dekken** [comment]
> @Dekken Why only the appveyor needs tf fix and not the osx and ubuntu docker files?

TF is not installed during Linux builds/TF is already installed so doesn't upgrade on Mac builds

Whereas on appveyor, TF is not already installed and installing it pulls down 2.0

We should see about version checking, and refactoring for tf v2

**Comment by sara-02** [comment]
> > @Dekken Why only the appveyor needs tf fix and not the osx and ubuntu docker files?
> 
> TF is not installed during Linux builds/TF is already installed so doesn't upgrade on Mac builds
> 
> Whereas on appveyor, TF is not already installed and installing it pulls down 2.0
> 
> We should see about version checking, and refactoring for tf v2

Oh, Ok. That makes sense.
Should we create an issue for tf v2 refactoring?
Also, how to trigger tests again for my PRs once this is merged?

**Comment by Dekken** [comment]
Issue is here: https://github.com/X-DataInitiative/tick/issues/408

Post merge, you can rebase your branch to master, then force push to your fork/branch

```
git pull https://github.com/X-DataInitiative/tick master --rebase
git push -f git@github.com:sara-02/tick $BRANCH
```

**Comment by sara-02** [comment]
@Dekken when can we expect to have this merged? :grin:

**Comment by Dekken** [comment]
done

**Pull request merged**
