### PR TITLE
version number increase

### PR DESCRIPTION
**Pull request by Dekken**

### CODE REVIEW

**Comment by Mbompr** [comment]
Do we want to change the version number in files appveyor.yml check_mkl.py and check_cblas.py for consistency?

**Comment by Dekken** [comment]
probably

**Comment by Dekken** [comment]
I''ve updated the manylinux base docker image as the one we were using was causing segfaults for me, plus the github page for it shows a different one

**Comment by Dekken** [comment]
how?

turns out the segfault is a debian thing, and the newer image is too new for auditwheel so I'm running it on ubuntu

**Pull request merged**
