### PR TITLE
test gtest/cmake on appveyor

### PR DESCRIPTION
**Pull request by Dekken**

### CODE REVIEW

**Comment by Mbompr** [comment]
This is running cpptest from python setup.py instead of cmake?

**Comment by Dekken** [comment]
cpptest runs cmake

**Comment by Mbompr** [comment]
I'm not getting what this does after #292

**Comment by Dekken** [comment]
previously gtests were done with mkn, which meant we built tick twice - with cpptests/cmake we should just be able to build once all going well

**Pull request merged**
