### PR TITLE
Fix issue 403, update keyview to list

### LINKED ISSUE #403: [Minor Fix][download_helper.py]
The line https://github.com/X-DataInitiative/tick/blob/6989fddb7117bdf9b7c9faa284f9d163a1bee140/tick/dataset/download_helper.py#L188 returns a KeyView which being a `set-like` object cannot be accessed directly via index.

`TypeError: 'KeysView' object does not support indexing`

A minor fix is need to change it to list/or iterator instead.
```python 
key_0  = list(dataset.keys())[0]
```

### PR DESCRIPTION
**Pull request by sara-02**
Fixes #403

### CODE REVIEW

**Comment by sara-02** [comment]
@Dekken @stephanegaiffas  The build failed at https://ci.appveyor.com/project/Dekken/tick-cyjm4/builds/27801229#L11446.
Could it be because of https://github.com/X-DataInitiative/tick/blob/35ad9f2f300138e9d928321745fa496c7ac0d38b/tools/docker/tick_ubuntu/Dockerfile#L23 where the latest version of `tensorflow` is getting installed ?

**Comment by Dekken** [comment]
it appears travis Mac builds have upgraded to TF2 also causing it to fail similarly to the appveyor build

**Comment by sara-02** [comment]
Should I raise a PR to add tf version in `osx_install.sh` ?

**Comment by Dekken** [comment]
if you would be so kind, in the interim as we decide what to do about TF2 at least

**Comment by sara-02** [comment]
@Dekken I did git fetch and rebase :/

**Comment by sara-02** [comment]
Finally, the checks have all passed. Kindly review the PR.

**Pull request merged**
