### PR TITLE
Fix kaplan_meier and nelson_aalen

### PR DESCRIPTION
**Pull request by thomasdes**
Fix kaplan_meier and nelson_aalen to take into account censored individuals which are still at risk in the sum of the  denominator

### CODE REVIEW

**Comment by deepPhong** [comment]
I have the following error when importing kaplan_meier; should I open up another issue?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d2d6de9d45d9> in <module>()
      8 
      9 from sklearn.linear_model import LogisticRegression
---> 10 from tick.survival import CoxRegression, kaplan_meier
     11 from lifelines import CoxPHFitter, KaplanMeierFitter
     12 from lifelines.plotting import add_at_risk_counts

~/.conda/envs/phong/lib/python3.5/site-packages/tick/__init__.py in <module>()
      1 # License: BSD 3 clause
      2 
----> 3 import tick.base

~/.conda/envs/phong/lib/python3.5/site-packages/tick/base/__init__.py in <module>()
     21 from tick.array import *
     22 from ..random import *
---> 23 from .timefunc import TimeFunction
     24 from .base import Base
     25 from .decorators import actual_kwargs

~/.conda/envs/phong/lib/python3.5/site-packages/tick/base/timefunc.py in <module>()
      3 from tick.base.build.base import TimeFunction as _TimeFunction
      4 import numpy as np
----> 5 from tick.base.base import Base
      6 
      7 

~/.conda/envs/phong/lib/python3.5/site-packages/tick/base/base.py in <module>()
    480 
    481 
--> 482 class Base(metaclass=BaseMeta):
    483     """The BaseClass of the tick project. This relies on some dark
    484     magic based on a metaclass. The aim is to have read-only attributes,

~/.conda/envs/phong/lib/python3.5/site-packages/tick/base/base.py in __new__(mcs, class_name, bases, attrs)
    414         classinfos[cls_key] = {'index': 0}
    415         extract_attrinfos = BaseMeta.extract_attrinfos
--> 416         classinfos[cls_key]['attr'] = extract_attrinfos(class_name, attrs)
    417 
    418         # Once we have collected all classinfos we can extract from it all

~/.conda/envs/phong/lib/python3.5/site-packages/tick/base/base.py in extract_attrinfos(class_name, attrs)
    293         # First we look at all documented attributes
    294         for attr_name, attr_doc in \
--> 295                 BaseMeta.find_documented_attributes(class_name, attrs):
    296             current_attrinfos.setdefault(attr_name, {})
    297             current_attrinfos[attr_name]['in_doc'] = True

~/.conda/envs/phong/lib/python3.5/site-packages/tick/base/base.py in find_documented_attributes(class_name, attrs)
    249 
    250         current_class_doc = inspect.cleandoc(attrs['__doc__'])
--> 251         parsed_doc = nd.docscrape.ClassDoc(None, doc=current_class_doc)
    252         attr_docs = parsed_doc['Parameters'] + parsed_doc['Attributes'] + \
    253             parsed_doc['Other Parameters']

AttributeError: module 'numpydoc' has no attribute 'docscrape'
```

**Comment by Dekken** [comment]
doesn't happen for me on master

**Comment by Mbompr** [comment]
@Dekken Didn't we notice that we are not compatible with numpydoc 0.8.0? 

@deepPhong Which version are you using? (`python -c "import numpydoc; print(numpydoc.__version__)"`)

**Comment by deepPhong** [comment]
@Mbompr I'm on v0.8.0

**Comment by Dekken** [comment]
that was docscrape and it's been fixed on master

**Comment by deepPhong** [comment]
I reinstalled everything from the repo instead of pip, it's now working

**Pull request merged**
