### PR TITLE
add badges for appveyor builds and gitter chat

### PR DESCRIPTION
**Pull request by Dekken**
#194

### CODE REVIEW

**Comment by Dekken** [comment]
No build required.

**Comment by Dekken** [comment]
Viewable [here](https://github.com/Dekken/tick/tree/badges)

**Comment by Mbompr** [comment]
Just thinking, shouldn't we add 
linux/Mac : travis badge
Windows: appveyor badge

Just to show explicitly that we support the three platforms :)

**Comment by Dekken** [comment]
Updated

**Pull request merged**
